# Generated by Django 4.2.16 on 2024-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                ("division_id", models.IntegerField(primary_key=True, serialize=False)),
                ("division_name", models.CharField(max_length=4, unique=True)),
            ],
            options={
                "db_table": "division",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("site_id", models.IntegerField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
                ("current_quantity", models.IntegerField()),
            ],
            options={
                "db_table": "site",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                (
                    "yard_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "yard",
                "managed": False,
            },
        ),
    ]
