# Generated by Django 4.2.16 on 2024-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.FloatField(primary_key=True, serialize=False),
                ),
                ("driver_id", models.CharField(max_length=10)),
                ("timestamp", models.IntegerField()),
                ("details", models.TextField()),
            ],
            options={
                "db_table": "transaction",
                "managed": False,
            },
        ),
    ]
