# Generated by Django 4.2.16 on 2024-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "equipment_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("equipment_type", models.CharField(max_length=10)),
                ("equipment_sort", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "equipment",
                "managed": False,
            },
        ),
    ]
