# Generated by Django 4.2.16 on 2024-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "driver_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "driver",
                "managed": False,
            },
        ),
    ]
